### ISSUE TITLE
Improve UI of editor footer

### ISSUE THREAD

**Issue by Shulammite-Aso** [publiclab/PublicLab.Editor#449] opened 2020-04-02 17:57 UTC
while #435 is looking at making the editor footer bar disappear when user starts typing, I think the UI of the footer could improve a bit. 
The bar looks a bit big. I'm thinking it can look sleekier. 

- We could reduce the height of the footer bar and size of Publish button, both on desktop and mobile view, but more especially the Mobile view.

- Add hover tooltip to the "more" button to indicate that clicking it presents edit history. (I didn't know i could view edit history here for sometime until i clicked it)

- Then i think adding hover effect to change color on "publish" button will be good idea too.

**Comment by NitinBhasneria** [comment] 2020-04-02 18:03
Yea, this is a part of making the Editor responsive. If you want you can work on this. 
Thanks

**Comment by Shulammite-Aso** [comment] 2020-04-02 19:01
Thank you @NitinBhasneria 

@VladimirMikulic @cesswairimu @jywarren you could give your view on this too

**Comment by VladimirMikulic** [comment] 2020-04-02 22:27
@Shulammite-Aso as @NitinBhasneria already said this is all under the umbrella of #435.
I am closing this since it is duplicate of #435.

**Closed by VladimirMikulic** 2020-04-02 22:27 UTC

**Comment by VladimirMikulic** [comment] 2020-04-02 22:28
@NitinBhasneria thank you for giving @Shulammite-Aso a shot at this issue.
@Shulammite-Aso I've assigned you at #435.

**Comment by Shulammite-Aso** [comment] 2020-04-03 01:15
Oh, okay. 

Only I thought his issue was only for making footer disappear once user starts typing. So I suggested here that the footer look and feel could be made better, apart from just making it disappear. 
I didn't know if he meant to also implement this in #435 .  But if he did, it's awesome too, I will start Working on it at once.

**Comment by VladimirMikulic** [comment] 2020-04-03 02:54
:+1:
