### ISSUE TITLE
Bad bug in /post editor (needs help tracing/reproducing)

### ISSUE THREAD

**Issue by ebarry** [publiclab/PublicLab.Editor#698] opened 2021-03-12 17:54 UTC
### The problem

While entering text into publiclab.org/post, two issues happen: 
1. when clicking into EITHER the title box OR the tag box, the cursor "jumps" /relocates itself to the the top left of the body text box
2. the Publish button is not operable

https://user-images.githubusercontent.com/161439/110978833-da0f3d00-8331-11eb-82b3-baa73b938755.mov

> What did you expect to see that you didn't?
1. I expected to be able to type a title, and type tags, without having the cursor move to another part of the editor. 
2. I expected to be able to click "Publish"

### Please show us where to look

https://publiclab.org/post

### What's your PublicLab.org username?

- purl
- amocorro 

### Browser, version, and operating system
Chrome (yes i see in the video that Purl's browser needs updating, it is now updated).

**Comment by jywarren** [comment] 2021-03-16 22:09
Noting that i can reproduce it in the example demo here. But adding console.log statements after the focus() calls i found above don't trigger, so it may not be those...

**Comment by jywarren** [comment] 2021-03-16 22:31
Gosh, i can't find any thing super obvious that would have been causing this. the `.focus()` lines seem not right, because running `.focus()` on the rich text area manually doesn't insert the cursor there. I wonder if it was a change to upstream `woofmark` link parsing that causes this. 

Fundamentally it looks like an event was handled too broadly -- i.e. clicking on /anything/ on the page after making a link causes the cursor to be moved to the rich text area. Let's see if Woofmark changes could have caused this:

https://github.com/jywarren/woofmark

YES - was able to reproduce this by booting that up in GitPod. Chasing it further down now....

**Comment by jywarren** [comment] 2021-03-16 22:41
OK, i believe it was this section:

https://github.com/jywarren/woofmark/blame/plots2/src/prompts/prompt.js#L70-L76

Trying to disable it.

**Comment by jywarren** [comment] 2021-03-16 22:46
Traced it to https://github.com/jywarren/woofmark/pull/3 -- let's revert, and debug another way!

**Comment by jywarren** [comment] 2021-03-16 22:46
It was orig a fix for https://github.com/publiclab/PublicLab.Editor/issues/407

**Comment by jywarren** [comment] 2021-03-16 22:48
Also noting that wasn't a major issue - the table insertion popover wasn't closing except when you manually close it. So i think we are OK to just revert!

**Comment by jywarren** [comment] 2021-03-16 23:01
Publishing as `v3.0.2`, i hope!

**Comment by jywarren** [comment] 2021-03-16 23:12
Published, this will resolve once the new code is pulled into `plots2`

**Comment by jywarren** [comment] 2021-03-16 23:12
https://www.npmjs.com/package/publiclab-editor

**Comment by jywarren** [comment] 2021-03-16 23:18
Solved in https://github.com/publiclab/plots2/pull/9323

**Closed** 2021-05-22 02:35 UTC
